apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: example-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: example-voting-app
  template:
    metadata: 
      name: postgres-pod
      labels:
        name: postgres-pod
        app: example-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"