apiVersion: v1
kind: Pod
metadata: 
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: example-voting-app
spec:
  containers:
    - name: voting-app-container
      image: jisaacs85/voting-app
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"