apiVersion: v1
kind: Pod
metadata: 
  name: worker-pod
  labels:
    name: worker-pod
    app: example-voting-app
spec:
  containers:
    - name: worker-app-container
      image: jisaacs85/worker-app
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"